image:
  file: .gitpod.Dockerfile

tasks:
  - name: Init
  - init: pip install -r requirements.txt
    command: python3 main.py

ports:
  - name: Hypercorn
    description: Hypercorn listening on 8000
    port: 8000
    onOpen: open-browser
