image:
  file: .gitpod.Dockerfile

tasks:
  - name: Init
  - init: pip install -r requirements.txt
    command: python3 main.py

ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview
